# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displayTemperature', '0003_auto_20170220_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=16)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_value',
            new_name='average',
        ),
        migrations.AddField(
            model_name='message',
            name='highest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='lowest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='device',
            field=models.ForeignKey(default='0000000000000000', on_delete=django.db.models.deletion.CASCADE, to='displayTemperature.Device'),
        ),
    ]
