# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayTemperature', '0004_auto_20170315_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
