# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayTemperature', '0006_auto_20170316_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='highest',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lowest',
        ),
        migrations.AddField(
            model_name='device',
            name='highest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='lowest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
